### PR TITLE
Added curl to automatic packages

### PR DESCRIPTION
**Pull request by TomOne**

### CODE REVIEW

**Comment by TomOne** [comment]
Don’t forget to merge this and my other pull requests:
https://github.com/ferventcoder/chocolateyautomaticpackages/pull/50
https://github.com/ferventcoder/nugetpackages/pull/105
https://github.com/ferventcoder/nugetpackages/pull/104
https://github.com/ferventcoder/nugetpackages/pull/100
https://github.com/ferventcoder/nugetpackages/pull/99
https://github.com/ferventcoder/nugetpackages/pull/98
https://github.com/ferventcoder/nugetpackages/pull/97

These pull requests are only small and don’t require much time.

**Comment by ferventcoder** [comment]
Curl is the one that I'm a bit worried about. Unless it behaves the same as
the current (no install script necessary as it contains everything in pkg),
then it's unlikely that I will merge it.

On Tuesday, November 26, 2013, TomOne wrote:

> Don’t forget to merge this and my other pull requests:
> #50 https://github.com/ferventcoder/chocolateyautomaticpackages/pull/50
> ferventcoder/nugetpackages#105https://github.com/ferventcoder/nugetpackages/pull/105
> ferventcoder/nugetpackages#104https://github.com/ferventcoder/nugetpackages/pull/104
> ferventcoder/nugetpackages#100https://github.com/ferventcoder/nugetpackages/pull/100
> ferventcoder/nugetpackages#99https://github.com/ferventcoder/nugetpackages/pull/99
> ferventcoder/nugetpackages#98https://github.com/ferventcoder/nugetpackages/pull/98
> ferventcoder/nugetpackages#97https://github.com/ferventcoder/nugetpackages/pull/97
> 
> These pull requests are only small and don’t require much time.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ferventcoder/chocolateyautomaticpackages/pull/46#issuecomment-29301524
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by TomOne** [comment]
Oh sorry, you’re right. Older curl versions get deleted on the website.

There exists a method for an automatic package that downloads the current curl version, extracts it and puts the files into the package. This could be a possible solution:
- Provide two Ketarin items: one called `a-curl` which downloads the latest version curl zip file, extracts the files using 7za and puts them into the `chocolateyautomaticpackages/curl/tools` folder.
- The other Ketarin item called `curl`, which builds and uploads the actual curl package using the files downloaded and extracted by `a-curl`
- If the `a-curl` Ketarin job fails, `curl` must fail too, otherwise it could happen that it uploads an empty package.

I know, this is quite a “dirty” way, but it’s because of Ketarin’s automation limitations. I use it already for my automatic [YUMI package](http://chocolatey.org/packages/yumi).

Would this method be OK for the curl package? Or do you have a better idea?

**Comment by ferventcoder** [comment]
Actually chocolatey autopackages now has a known script it looks for to run arbitrary powershell, which could download and arrange the files.

**Comment by ferventcoder** [comment]
Look at the release notes here - http://chocolatey.org/packages/ChocolateyPackageUpdater

**Comment by TomOne** [comment]
How does it work?
I placed a `ChocoPkgUp.ps1` file into the curl package folder (`C:\Chocolatey\chocolateyautomaticpackages\curl` in this case), but it doesn’t get executed by `chocopkgup`. Is there a special option that needs to be added to chocopkgup? The output of `chocopkgup --help` doesn’t mention it, and also the text from the [release notes](http://chocolatey.org/packages/ChocolateyPackageUpdater) doesn’t provide additional information.

**Comment by TomOne** [comment]
@ferventcoder, can you give me an answer for my previous question? I would like to conclude this PR and the others.

**Comment by ferventcoder** [comment]
Perhaps it is a bug in the tool. It should copy it over to the output folder and then run the ps1 file.

**Comment by TomOne** [comment]
Can you reproduce this bug?

**Comment by TomOne** [comment]
Can you fix this bug?

**Comment by ferventcoder** [comment]
I will take a look at it later today or tomorrow. I hit the high priority items

**Comment by TomOne** [comment]
Thanks :+1:

**Comment by ferventcoder** [comment]
Closing as this has been moved out of this repo.

**Pull request closed without merging**
