### PR TITLE
Converted sliksvn to automatic package and added better icon

### PR DESCRIPTION
**Pull request by TomOne**

### CODE REVIEW

**Comment by TomOne** [comment]
Again you accidentally updated your deprecated manual sliksvn package instead of the automatic one. Consider this PR: https://github.com/ferventcoder/nugetpackages/pull/123

I hope you now understand better now why it’s [not a good idea](https://groups.google.com/forum/#!topic/chocolatey/iECDfblM290) to keep two separate repos for manual and automatic packages. :smiley:

**Comment by ferventcoder** [comment]
I didn't do anything with sliksvn in the last couple of weeks.

On Thursday, May 22, 2014, TomOne notifications@github.com wrote:

> Again you accidentally updated your deprecated manual sliksvn package
> instead of the automatic one. Consider this PR:
> ferventcoder/nugetpackages#123https://github.com/ferventcoder/nugetpackages/pull/123
> 
> I hope you now understand better now why it’s not a good ideahttps://groups.google.com/forum/#!topic/chocolatey/iECDfblM290to keep two separate repos for manual and automatic packages. [image:
> :smiley:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ferventcoder/chocolateyautomaticpackages/pull/68#issuecomment-43853829
> .

## 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by TomOne** [comment]
I don’t think so: https://github.com/ferventcoder/nugetpackages/commit/ccfbaf8fe2bd09122da8d653de4bb92f4ce2db20

My PR to move sliksvn to the automatic packages was on 2014-02-27, so you forgot to merge https://github.com/ferventcoder/nugetpackages/pull/123 and edited the deprecated manual package instead of the one in the automatic repository.

**Comment by ferventcoder** [comment]
A month ago. Okay. You already chastised me on that one ;)

On Thursday, May 22, 2014, TomOne notifications@github.com wrote:

> Actually you did exactly that: ferventcoder/nugetpackages@ccfbaf8https://github.com/ferventcoder/nugetpackages/commit/ccfbaf8fe2bd09122da8d653de4bb92f4ce2db20
> 
> My PR to move sliksvn to the automatic packages was on 2014-02-27, so you
> forgot to merge ferventcoder/nugetpackages#123https://github.com/ferventcoder/nugetpackages/pull/123and edited the deprecated manual package instead of the one in the
> automatic repository.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ferventcoder/chocolateyautomaticpackages/pull/68#issuecomment-43889388
> .

## 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by TomOne** [comment]
Nope, that was about [phantomjs](https://github.com/ferventcoder/nugetpackages/pull/124).

**Comment by TomOne** [comment]
:+1: for one package repository instead of two :smiley:

**Comment by ferventcoder** [comment]
Not arguing the point. :)

**Pull request merged**
