### PR TITLE
Updating MySQL to take account of new installer location

### PR DESCRIPTION
**Pull request by zagarachi**
The msi now has a different name and location on dev.mysql.com
Changed to zip file as its more consistant.

### CODE REVIEW

**Comment by ferventcoder** [comment]
That would not be enough for the package to actually install. Since it expects an MSI, what is it going to do with the .zip?

**Comment by zagarachi** [comment]
I was looking at that, I did originally have it pointing at the msi http://dev.mysql.com/get/Downloads/MySQLInstaller/mysql-installer-community-5.6.19.0.msi

however the chocolatey install script actually ignores this anyway does it not? looking at https://github.com/ferventcoder/chocolateyautomaticpackages/blob/master/mysql/tools/chocolateyInstall.ps1 it hard codes it to:

`$url = 'http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-{{PackageVersion}}-win32.zip'`
`$url64 = 'http://cdn.mysql.com/Downloads/MySQL-5.6/mysql-{{PackageVersion}}-winx64.zip'`

I assumed that the ketarin job was just to trigger the build of the package on your buildserver?

I am pretty sure that the install just uses the zip file and not an msi

**Comment by ferventcoder** [comment]
@zagarachi You are correct! I didn't realize it was changed from a zip originally without fixing the chocolateyInstall.ps1. Thanks for providing this fix!

**Comment by zagarachi** [comment]
Can you accept either this pull request or this other one https://github.com/ferventcoder/chocolateyautomaticpackages/pull/82 which does the same job?

**Comment by ffMathy** [comment]
Yes, that would be nice. I'm in desperate need of getting this package working.

**Comment by ferventcoder** [comment]
This has been fixed and pushed. Still need to update the ketarin job to take account for the changes though.

**Pull request merged**
