### PR TITLE
Lockhunter as automatic package

### PR DESCRIPTION
**Pull request by TomOne**
Tested and working!

### CODE REVIEW

**Comment by ferventcoder** [comment]
hmmm

**Comment by TomOne** [comment]
> hmmm

Is there a problem with this pull request? Please let me know.

**Comment by ferventcoder** [comment]
Not that I'm aware of. I'm just slow on PRs sometimes.

On Sunday, December 1, 2013, TomOne wrote:

> hmmm
> 
> Is there a problem with this pull request? Please let me know.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ferventcoder/chocolateyautomaticpackages/pull/50#issuecomment-29572238
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
From now on when you create the ketarin.xml files I want it to be in the format _packageName_.ketarin.xml

**Comment by ferventcoder** [comment]
Fixed lockhunter chocolateyinstall.ps1 as well. I made changes to it that were not in this version (recent changes).

**Comment by TomOne** [comment]
> From now on when you create the ketarin.xml files I want it to be in the format packageName.ketarin.xml

I know. I think I made this PR before you renamed the XML files.

**Comment by ferventcoder** [comment]
Oh money. :)

On Wed, Jan 1, 2014 at 10:38 AM, TomOne notifications@github.com wrote:

> From now on when you create the ketarin.xml files I want it to be in the
> format packageName.ketarin.xml
> 
> I know. I think I made this PR before you renamed the XML files.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ferventcoder/chocolateyautomaticpackages/pull/50#issuecomment-31425509
> .

## 

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Pull request merged**
