### PR TITLE
Fixed Sykpe package, fixed issues with icons

### PR DESCRIPTION
**Pull request by TomOne**
I know you are thinking about proposal to use the msi version of skype. But it’s surely not wrong to update your current Skype package.

### CODE REVIEW

**Comment by ferventcoder** [comment]
:)

**Comment by ferventcoder** [comment]
can you update this pull request please?

**Comment by TomOne** [comment]
Is that even necessary? It should be possible to discard this commit https://github.com/ferventcoder/chocolateyautomaticpackages/commit/55a5bc6e922a5a22bdd8a6f68e151f1631982898 as it is deprecated now.

I think the other commits are fine and wouldn’t break anything.

**Comment by ferventcoder** [comment]
Problem is that you committed unrelated things with that commit (the
removal of postgre gif files).

On Saturday, June 8, 2013, TomOne wrote:

> Is that even necessary? It should be possible to discard this commit
> 55a5bc6https://github.com/ferventcoder/chocolateyautomaticpackages/commit/55a5bc6e922a5a22bdd8a6f68e151f1631982898as it is deprecated now.
> 
> I think the other commits are fine and wouldn’t break anything.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ferventcoder/chocolateyautomaticpackages/pull/13#issuecomment-19155129
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by TomOne** [comment]
You are right, that was unrelated, even if the icon link of the postgresql package is broken: https://chocolatey.org/packages/postgresql

**Comment by TomOne** [comment]
What solution do you suggest?

**Comment by TomOne** [comment]
This pull request is deprecated.

**Pull request closed without merging**
