### PR TITLE
added x64 source to vlc

### PR DESCRIPTION
**Pull request by TheOneRing**

### CODE REVIEW

**Comment by ferventcoder** [comment]
Does it work now and is not considered beta?

**Comment by TheOneRing** [comment]
It is still not considered as stable but I'm using it for two years now without problems.

**Comment by ferventcoder** [comment]
It would need to be in a prerelease version then. If the authors don't
consider it stable, it shouldn't be part of the stable feed.

On Sunday, November 10, 2013, TheOneRing wrote:

> It is still not considered as stable but I'm using it for two years now
> without problems.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ferventcoder/chocolateyautomaticpackages/pull/53#issuecomment-28164573
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by TheOneRing** [comment]
I just asked, it is considered as stable even so the direct link on videolan.org only points to the 32 bit version.

**Comment by ferventcoder** [comment]
Cool

On Mon, Nov 11, 2013 at 3:40 AM, TheOneRing notifications@github.comwrote:

> I just asked, it is considered as stable even so the direct link on
> videolan.org only points to the 32 bit version.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ferventcoder/chocolateyautomaticpackages/pull/53#issuecomment-28184501
> .

## 

---

Rob
"Be passionate in all you do"

http://devlicio.us/blogs/rob_reynolds
http://ferventcoder.com
http://twitter.com/ferventcoder

**Comment by ferventcoder** [comment]
Pulling this in. Thanks for the contribution!

**Pull request merged**
