### PR TITLE
Replaced some icons, corrected icon urls

### PR DESCRIPTION
**Pull request by TomOne**

### CODE REVIEW

**Comment by ferventcoder** [comment]
Missed some?

**Comment by TomOne** [comment]
I'm not sure what you mean here. The 7Zip-icon was broken because GitHub changed the raw url format.

**Comment by ferventcoder** [comment]
Issuing pull requests from the same branch causes issues. Have you had any opportunity to look into how to do branching and issuing pull requests from those? If not I'd be happy to point out some resources... :)

**Comment by TomOne** [comment]
OK, next time I will do that.

**Pull request merged**
